#!/bin/bash

lock() {
    i3lock --color=1d2021 --insidevercolor=689d6aff --insidewrongcolor=fb4934ff --insidecolor=1d2021ff --ringvercolor=689d6aff --ringwrongcolor=fb4934ff --ringcolor=fabd2fff --textcolor=ebdbb2ff --separatorcolor=fabd2fff --keyhlcolor=689d6aff --bshlcolor=689d6aff --timestr="%H:%M" --datestr="%a %d %b" -k
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|reboot|shutdown}"
        exit 2
esac

exit 0

