#! /bin/sh

# ~/.config/bspwm/bspwmrc
# -------------------------------------
# bspwm configuration file



# startup configs and scripts

#/usr/lib/gnome-settings-daemon/gsd-xsettings &

redshift &
sxhkd &

$HOME/.bin/lock.sh

. "$HOME/.wallpapers/current.sh"

bspc monitor eDP1 -d 1 2 3 4 5 6
bspc monitor HDMI1 -d 7 8 9 0

# config

bspc config border_width                2
bspc config window_gap                  34
bspc config split_ratio                 0.54
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config single_monocle              true
bspc config focus_follows_pointer       true
bspc config click_to_focus              true
bscp config remove_disabled_monitors    true
bscp config remove_unplugged_monitors   true

bspc config normal_border_color         "$color0"
bspc config active_border_color         "$color7"
bspc config focused_border_color        "$color15"
bspc config presel_border_color         "$color6"



# rules

bspc rule -a mpv                state=floating
bspc rule -a feh                state=floating
bspc rule -a Zathura            state=tiled

