icons_format = "{icon}"

[theme]
theme = "native"

[icons]
icons = "awesome6"
# [icons.overrides]
# bat = ["|E|", "|_|", "|=|", "|F|"]
# bat_charging = "|^| "

[[block]]
block = "backlight"

[[block]]
block = "sound"
format = " $icon {$volume|}  {$output_description|}  "
show_volume_when_muted = true
# [[block.click]]
# button = "left"
# cmd = "pavucontrol"

[[block]]
block = "battery"
driver = "upower"
format = " $icon    $percentage  {$time |} "
full_format = " $icon   "

[[block]]
block = "disk_space"
alert_unit = "GB"
warning = 20.0
alert = 10.0
format = " $icon   $available.eng(w:3)  "
format_alt = " $icon   $free.eng(w:3)  $used.eng(w:3)  "

[[block]]
block = "time"
[block.format]
full = "  $timestamp.datetime(f:'%Y-%m-%d  %a  %R')  "
short = "  $timestamp.datetime(f:%R)  "

