#!/bin/bash

. "${HOME}/.cache/wal/colors.sh"

bg_image=/home/andreas/Pictures/wp.png
bg_inside="${color0}99"
bg_ver="${color5}44"
bg_wrong="${color5}44"
fg_ring="${color0}ff"
fg_ver="${color5}ff"
fg_wrong="${color5}ff"
fg_action="${color5}ff"
fg_text="${color5}ff"
fg_text_str="${color7}ff"



lock() {
    i3lock --insidevercolor=$bg_ver --insidewrongcolor=$bg_wrong --insidecolor=$bg_inside --ringvercolor=$fg_ver --ringwrongcolor=$fg_wrong --ringcolor=$fg_ring --linecolor=$fg_ring --separatorcolor=$fg_action --textcolor=$fg_text --keyhlcolor=$fg_action --bshlcolor=$fg_action -s --screen 0 --clock --indicator --composite --blur=8 --timestr="%H:%M" --timepos="ix-200:iy-80" --timecolor=$fg_text_str --timefont="Oswald" --timesize=112 --datestr="%A, %d" --datepos="ix-200:iy-30" --datecolor=$fg_text --datefont="Oswald" --datesize=48 --veriftext="ʘ‿ʘ" --wrongtext="ʘ_ʘ" --textsize=40 --modsize=114 --radius=80
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|reboot|shutdown}"
        exit 2
esac

exit 0

