#!/bin/bash

bg_global=1b2b34
bg_inside=1b2b34ff
fg_text=ded8ccff
fg_ring=fac863ff
fg_wrong=ed5f67ff
fg_action=ded8ccff
fg_ver=6699ccff

lock() {
    i3lock --color=$bg_global --insidevercolor=$bg_inside --insidewrongcolor=$bg_inside --insidecolor=$bg_inside --ringvercolor=$fg_ver --ringwrongcolor=$fg_wrong --ringcolor=$fg_ring --textcolor=$fg_text --separatorcolor=$fg_ring --keyhlcolor=$fg_action --bshlcolor=$fg_action --timestr="%H:%M" --datestr="%a %d %b" -k
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|reboot|shutdown}"
        exit 2
esac

exit 0

