
[[battery.display]]
threshold = 10
style = "#ee5588"

[[battery.display]]
threshold = 30
style = "yellow"

[character]
success_symbol = "[❯](#ff77bb)"
# error_symbol = "[✖](#ff6699)"
error_symbol = "[✖](#ee5588)"
vicmd_symbol = "[❮](#ff77bb)"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[directory]
truncation_length = 8
truncate_to_repo = false
style = "#66bbff"

[time]
disabled = false
format = "[$time]($style) "
style = "#646464"

