#! /bin/sh

# ~/.config/bspwm/bspwmrc
# -------------------------------------
# bspwm configuration file



# startup configs and scripts

#xrandr --output HDMI-1 --dpi 100 --right-of eDP-1 &
xrandr --output eDP-1 --dpi 200 --primary &

xsetroot -cursor_name left_ptr &
setxkbmap -layout "gb,es" -option "grp:shifts_toggle" &

#feh --bg-tile ~/Pictures/wp.png --no-fehbg &
feh --bg-fill ~/Pictures/wp.png --no-fehbg &

/usr/lib/gnome-settings-daemon/gsd-xsettings &

redshift &

~/.bin/launch_compton &
~/.bin/launch_polybar &

sxhkd &

bspc monitor eDP-1 -d 1 2 3 4 5 6
bspc monitor HDMI-1 -d 7 8 9 0



# config

bspc config border_width            2
bspc config window_gap              34
bspc config split_ratio             0.54
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config click_to_focus          true
bspc config single_monocle          true

bspc config normal_border_color     "#1b2b34"
bspc config active_border_color     "#c0c5ce"
bspc config focused_border_color    "#c0c5ce"
bspc config presel_feedback_color   "#5fb3b3"
bspc config urgent_border_color     "#ec5f67"



# rules

bspc rule -a mpv                state=floating
bspc rule -a File-roller        state=floating
bspc rule -a Tilix              state=floating
bspc rule -a Google-chrome      desktop=^1
bspc rule -a jetbrains-idea-ce  desktop=^2
bspc rule -a jetbrains-studio   desktop=^2
bspc rule -a Gnome-builder      desktop=^2

