#! /bin/sh

# ~/.config/bspwm/bspwmrc
# -------------------------------------
# bspwm configuration file



sxhkd &

bspc monitor -d I II III IV V



# config
bspc config border_width            4
bspc config window_gap              34
bspc config split_ratio             0.54
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config click_to_focus          true
bspc config single_monocle          true

bspc config normal_border_color     "#1b2b34"
bspc config active_border_color     "#c0c5ce"
bspc config focused_border_color    "#c0c5ce"
bspc config presel_feedback_color   "#5fb3b3"
bspc config urgent_border_color     "#ec5f67"



# rules
bspc rule -a mpv                state=floating
bspc rule -a Google-chrome      desktop=^1
bspc rule -a jetbrains-idea-ce  desktop=^2
bspc rule -a jetbrains-studio   desktop=^2
bspc rule -a Gnome-builder      desktop=^2

